- name: remove docker bin from /usr/bin
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/bin/runc
    - /usr/bin/ctr
    - /usr/bin/containerd
    - /usr/bin/containerd-shim
    - /usr/bin/docker
    - /usr/bin/dockerd
    - /usr/bin/docker-proxy
    - /usr/bin/docker-init
