---
- name: install chrony
  apt: 
    name: ["chrony"]
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no

- name: configure chrony 
  template: 
    src: chrony.conf.j2 
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: restart chrony

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: start the chrony service
  service: 
    name: chronyd 
    state: started 
    enabled: yes
