---
depends_repo_url: 
  - "{{ url_prefix }}/centos8/BaseOS"
  - "{{ url_prefix }}/centos8/AppStream"
docker_repo_url: "{{ url_prefix }}/linux_soft/yum/docker-ce"
podman_repo_url: "{{ url_prefix }}/linux_soft/yum/podman"
