---
- name: apply metrics-server
  shell: kubectl -s {{ kubernetes_apiserver }} apply -f /var/tmp/metrics-server/{{ metrics_server_version.split('.')[:2] | join('.') }}/{{ item }}
  loop:
    - metrics-server.yaml
