---
- name: delete metrics-server
  shell: kubectl -s {{ kubernetes_apiserver }} delete -f /var/tmp/metrics-server/{{ metrics_server_version.split('.')[:2] | join('.') }}/{{ item }}
  loop:
    - metrics-server.yaml
  failed_when: false

- name: remove metrics-server yaml
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/tmp/metrics-server
