---
- name: create calico yaml dir
  file:
    path: /var/tmp/calico/{{ calico_version.split('.')[:2] | join('.') }}
    state: directory
    owner: root
    group: root
    mode: 0755

- name: sync calico yaml
  template: 
    src: "{{ calico_version.split('.')[:2] | join('.') }}/{{ item.src }}"
    dest: /var/tmp/calico/{{ calico_version.split('.')[:2] | join('.') }}/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: calico.yaml.j2, dest: calico.yaml }
  notify: apply calico

- name: create calicoctl config dir
  file:
    path: /etc/calico/tls/etcd
    state: directory
    owner: root
    group: root
    mode: 0755

- name: sync etcd tls certs
  copy:
    src: "tls/etcd/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'ca.pem', dest: '/etc/calico/tls/etcd/ca.pem' }
    - { src: 'server.pem', dest: '/etc/calico/tls/etcd/server.pem' }
    - { src: 'server-key.pem', dest: '/etc/calico/tls/etcd/server-key.pem' }

- name: fetch calicoctl binary to PATH(/usr/local/bin)
  get_url:
    url: "{{ calicoctl_binary_url }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755

- name: sync calico_ipv4pool_cidr.yaml
  template:
    src: "{{ calico_version.split('.')[:2] | join('.') }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: calico_ipv4pool_cidr.yaml.j2, dest: "/var/tmp/calico/{{ calico_version.split('.')[:2] | join('.') }}/calico_ipv4pool_cidr.yaml" }
    - { src: calicoctl.cfg.j2, dest: "/etc/calico/calicoctl.cfg" }
  notify: 
    - add calico-ippool
    - delete default-calico-ippool
