---
- name: install crio depends (libseccomp-devel)
  yum: 
    name: libseccomp-devel
    state: present
    update_cache: yes

- import_tasks: runc.yml
  tags: runc

- name: create crio dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/crio
    - /etc/containers/oci/hooks.d
    - /var/lib/crio
    - /var/lib/containers/storage
    - /var/log/crio/pods

- name: get crio to PATH
  get_url:
    url: "{{ crio_bin_url }}/{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  loop:
    - crio
    - crio-config
    - pause
  when: crio_version is version('v1.16.0', '<')

- name: get crio to PATH
  get_url:
    url: "{{ crio_bin_url }}/{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  loop:
    - crio
    - crio-status
    - pause
  when: crio_version is version('v1.16.0', '>=') and crio_version is version('v1.17.0', '<')

- name: get crio to PATH
  get_url:
    url: "{{ crio_bin_url }}/{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  loop:
    - crio
    - crio-status
    - pinns
  when: crio_version is version('v1.17.0', '>=')

- name: get conmon to PATH
  get_url:
    url: "{{ conmon_bin_url }}/{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  loop:
    - conmon

- name: create /lib/systemd/system/crio.service
  template:
    src: "{{ crio_version.split('.')[:2] | join('.') }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: crio.j2, dest: /etc/default/crio }
    - { src: crio.conf.j2, dest: /etc/crio/crio.conf }
    - { src: crio.service.j2, dest: /lib/systemd/system/crio.service }
    - { src: policy.json.j2, dest: /etc/containers/policy.json }
  notify: restart crio

- name: create /lib/systemd/system/crio-shutdown.service
  template:
    src: "{{ crio_version.split('.')[:2] | join('.') }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: crio-shutdown.service.j2, dest: /lib/systemd/system/crio-shutdown.service }
  notify: restart crio-shutdown

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: start crio
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  loop:
    - crio
    - crio-shutdown
