---
- name: add centos{{ ansible_distribution_major_version|int }} repo
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: no
    state: present
  loop:
    - { name: "centos{{ ansible_distribution_major_version|int }}", description: "centos{{ ansible_distribution_major_version|int }} YUM repo", baseurl: "{{ depends_repo_url }}" }
    - { name: podman, description: podman, baseurl: "{{ podman_repo_url }}" }
