---
- name: 127.0.0.53 in /etc/resolv.conf ?
  raw: grep 127.0.0.53 /etc/resolv.conf
  register: result_127
  failed_when: false

- name: systemd-resolved is running ?
  raw: pidof systemd-resolved
  register: result_resolved
  failed_when: false

- name: disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no
  when: not result_127.rc and not result_resolved.rc

- name: link /etc/resolv.conf --> /run/systemd/resolve/resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  when: not result_127.rc and not result_resolved.rc
