---
- name: delete kubedns 
  shell: kubectl -s {{ kubernetes_apiserver }} delete -f /var/tmp/kubedns/
  ignore_errors: true

- name: remove kubedns yaml
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/tmp/kubedns
