---
- name: install podman depends (ostree)
  apt: 
    name: ['libostree-dev', 'libseccomp-dev']
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no

- name: link libdevmapper.so.1.02
  file:
    src: /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1
    dest: /lib/x86_64-linux-gnu/libdevmapper.so.1.02
    owner: root
    group: root
    state: link
