---
- name: create cni config dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /opt/cni/bin
    - /etc/cni/net.d

- name: fetch and extract cni-plugins-linux-amd64-{{ cni_version }}.tgz into /opt/cni/bin
  unarchive:
    src: "{{ cni_binary_url }}"
    dest: /opt/cni/bin
    remote_src: yes
  register: download
  until: download is not failed
  retries: 5
