---
- name: sync flannel cni 10-flannel.conflist
  template: 
    src: "{{ flannel_version.split('.')[:2] | join('.') }}/10-flannel.conflist.j2"
    dest: /etc/cni/net.d/10-flannel.conflist
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{ item }}"
  loop: "{{ groups['kubernetes_node'] }}"

- name: create flannel yaml dir
  file:
    path: /var/tmp/flannel/{{ flannel_version.split('.')[:2] | join('.') }}
    state: directory
    owner: root
    group: root
    mode: 0755

- name: sync flannel yaml
  template: 
    src: "{{ flannel_version.split('.')[:2] | join('.') }}/{{ item.src }}"
    dest: /var/tmp/flannel/{{ flannel_version.split('.')[:2] | join('.') }}/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: kube-flannel.yaml.j2, dest: kube-flannel.yaml }
  notify: apply flannel
