---
- name: delete flannel
  shell: kubectl -s {{ kubernetes_apiserver }} delete -f /var/tmp/flannel/{{ flannel_version.split('.')[:2] | join('.') }}/{{ item }}
  with_items:
    - kube-flannel.yaml
  async: 10
  ignore_errors: true

- name: remove flannel yaml
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/tmp/flannel
    - /run/flannel
