---
- name: delete flannel
  shell: kubectl -s {{ kubernetes_apiserver }} delete -f /var/tmp/flannel/{{ flannel_version.split('.')[:2] | join('.') }}/{{ item }}
  with_items:
    - kube-flannel.yaml
  failed_when: false

- name: remove flannel yaml
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/tmp/flannel
    - /run/flannel

- name: remove cni conf
  file:
    path: /etc/cni
    state: absent
  delegate_to: "{{ item }}"
  loop: "{{ groups['kubernetes_node'] }}"

- name: remove cni bin
  file:
    path: /opt/cni
    state: absent
  delegate_to: "{{ item }}"
  loop: "{{ groups['kubernetes_node'] }}"

- name: clear flannel network interfaces
  raw: |
      ifconfig cni0 down ;\
      ip link delete cni0
  failed_when: false
  delegate_to: "{{ item }}"
  loop: "{{ groups['kubernetes_node'] }}"

