---
- name: delete flannel
  shell: kubectl -s {{ kubernetes_apiserver }} delete -f /var/tmp/flannel/{{ flannel_version.split('.')[:2] | join('.') }}/{{ item }}
  with_items:
    - kube-flannel.yaml
  async: 10
  ignore_errors: true

- name: remove flannel yaml
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/tmp/flannel
    - /run/flannel
    - /etc/cni/net.d/10-flannel.conflist
  delegate_to: "{{ item }}"
  loop: "{{ groups['kubernetes-node'] }}"

- name: clear flannel network interfaces
  raw: |
      ifconfig cni0 down ;\
      ip link delete cni0
  failed_when: false
  delegate_to: "{{ item }}"
  loop: "{{ groups['kubernetes-node'] }}"

