---
- name: unmount left kata dirs
  raw: umount overlay
  failed_when: false
  tags: unmount

- name: remove kata-containers
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /opt/kata
    - /usr/local/bin/containerd-shim-kata-v2
    - /run/kata-containers
