---
- name: filter mounted pod dirs
  shell: df
  register: df_result

- name: unmount left pods 
  mount:
    path: "{{ item }}"
    state: unmounted
  loop: "{{ df_result.stdout | regex_findall('(/var/lib/kubelet/pods/.+)') }}"

- name: filter mounted kata-containers dirs
  shell: df
  register: df_result

- name: unmount left kata-containers
  mount:
    path: "{{ item }}"
    state: unmounted
  loop: "{{ df_result.stdout | regex_findall('(/run/kata-containers/.+)') }}"

- name: unmount left kata dirs
  raw: umount overlay
  failed_when: false
  tags: unmount

- name: remove kata-containers
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /opt/kata
    - /usr/local/bin/containerd-shim-kata-v2
    - /run/kata-containers
    - /etc/kata-containers
