---
- name: label kubernetes-node "beta.kubernetes.io/fluentd-ds-ready=true"
  shell: kubectl -s {{ kubernetes_apiserver }} label nodes --overwrite=true $(kubectl -s {{ kubernetes_apiserver }} get nodes -ojsonpath='{.items[*].metadata.name}') 'beta.kubernetes.io/fluentd-ds-ready=true'

- name: create efk yaml dir
  file:
    path: /var/tmp/efk/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: sync fluentd conf yaml
  copy: 
    src: "{{ item.src }}"
    dest: /var/tmp/efk/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: fluentd-es-configmap.yaml, dest: fluentd-es-configmap.yaml }

- name: sync efk yaml
  template: 
    src: "{{ item.src }}"
    dest: /var/tmp/efk/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: es-statefulset.yaml.j2, dest: es-statefulset.yaml }
    - { src: es-service.yaml.j2, dest: es-service.yaml }
    - { src: fluentd-es-ds.yaml.j2, dest: fluentd-es-ds.yaml }
    - { src: kibana-deployment.yaml.j2, dest: kibana-deployment.yaml }
    - { src: kibana-service.yaml.j2, dest: kibana-service.yaml }
  notify: apply efk
