---
- name: create coredns yaml dir
  file:
    path: /var/tmp/coredns/{{ coredns_version.split('.')[:2] | join('.') }}
    state: directory
    owner: root
    group: root
    mode: 0755

- name: sync coredns yaml
  template: 
    src: "{{ coredns_version.split('.')[:2] | join('.') }}/{{ item.src }}"
    dest: /var/tmp/coredns/{{ coredns_version.split('.')[:2] | join('.') }}/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: coredns.yaml.j2, dest: coredns.yaml }
    - { src: dns-horizontal-autoscaler.yaml.j2, dest: dns-horizontal-autoscaler.yaml }
  notify: apply coredns
