---
- name: add centos7 repo
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: no
    state: present
  loop:
    - { name: centos7, description: centos7 YUM repo, baseurl: "{{ depends_repo_url }}" }
    - { name: podman, description: podman, baseurl: "{{ podman_repo_url }}" }
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

- name: add ubuntu repo
  apt_repository:
    repo: deb {{ depends_repo_url }} xenial repo
    state: present
    filename: dce-offline.list
  when: ansible_os_family == "Debian" and ansible_distribution == "xenial"
