---
- import_tasks: hostname.yml
  tags: hostname
- import_tasks: timezone.yml
  tags: timezone
- import_tasks: swapoff.yml
  tags: swapoff
- import_tasks: limits.yml
  tags: limits
- include_tasks: "{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/{{ task_item }}"
  loop: 
    - security.yml
    - sysctl.yml
  loop_control:
    loop_var: task_item
  tags: sysctl
