---
- name: delete calico 
  shell: kubectl -s {{ kubernetes_apiserver }} delete -f /var/tmp/calico/{{ calico_version.split('.')[:2] | join('.') }}/{{ item }}
  with_items:
    - calico.yaml
    - rbac.yaml
  failed_when: false

- name: remove calico yaml
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/calicoctl
    - /etc/calico
    - /var/tmp/calico

- name: remove cni conf
  file:
    path: /etc/cni
    state: absent
  delegate_to: "{{ item }}"
  loop: "{{ groups['kubernetes-node'] }}"

- name: remove cni bin
  file:
    path: /opt/cni
    state: absent
  delegate_to: "{{ item }}"
  loop: "{{ groups['kubernetes-node'] }}"

- name: clear calico network interfaces
  raw: |
      ifconfig tunl0 down ;\
      ip link delete tunl0
  failed_when: false
  delegate_to: "{{ item }}"
  loop: "{{ groups['kubernetes-node'] }}"

