- name: install docker bin to /usr/bin
  copy:
    remote_src: yes
    src: /tmp/docker/{{ item }}
    dest: /usr/bin
    owner: root
    group: root
    mode: 0755
  loop:
    - docker
    - dockerd
    - docker-init
    - docker-proxy
    - docker-runc
    - docker-containerd
    - docker-containerd-ctr
    - docker-containerd-shim
