---
- name: stop the flannel service
  service: 
    name: flanneld 
    state: stopped 
    enabled: no
  ignore_errors: true

- name: uninstall flannel
  yum: 
    name: flannel
    state: absent

- name: remove cni
  file: 
    path: "{{ item }}"
    state: absent
  loop:
    - /lib/systemd/system/flanneld.service
    - /run/flannel
    - /etc/cni
    - /etc/flannel
    - /opt/cni
    - /var/log/flannel

- name: clear flannel network in etcd
  raw: |
      etcdctl --endpoints={% for item in groups['etcd'] %}https://{{ hostvars[item]['inventory_hostname'] }}:2379{% if not loop.last %},{% endif %}{% endfor %} \
      --ca-file=/etc/etcd/tls/ca.pem \
      --cert-file=/etc/etcd/tls/server.pem \
      --key-file=/etc/etcd/tls/server-key.pem \
      rm -r /{{ FLANNEL_ETCD_PREFIX }}
  delegate_to: "{{ groups['etcd'][0] }}"
  failed_when: false

- name: clear flannel network interfaces
  raw: |
      ifconfig cni0 down ;\
      ifconfig flannel.1 down ;\
      ip link delete cni0 ;\
      ip link delete flannel.1
  failed_when: false

