---
- include_tasks: centos/docker_uninstall.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
- include_tasks: debian/docker_uninstall.yml
  when: ansible_os_family == "Debian"
