---
- name: remove debian {{ ansible_distribution_release }} offline repo
  apt_repository:
    repo: deb [trusted=yes] {{ item }} {{ ansible_distribution_release }} main contrib 
    state: absent
    update_cache: no
    validate_certs: no
    filename: debian-offline
  loop: "{{ depends_repo_url }}"

- name: remove debian {{ ansible_distribution_release }} online repo (tsinghua)
  apt_repository:
    repo: deb {{ item.mirror }} {{ item.codename }} main contrib non-free
    state: absent
    update_cache: no
    validate_certs: no
    filename: debian
  loop:
    - { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}" }
    - { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}-updates" }
    - { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}-proposed-updates" }
    - { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}-backports" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}-updates" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}-proposed-updates" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}-backports" }
  ignore_errors: true
  when: not debian_offline
