---
- name: add debian {{ ansible_distribution_release }} offline repo
  apt_repository:
    repo: deb [trusted=yes] {{ depends_repo_url }} {{ ansible_distribution_release }} main contrib 
    state: present
    update_cache: yes
    validate_certs: no
    filename: debian
  when: debian_offline

- name: add debian {{ ansible_distribution_release }} online repo (tsinghua/aliyun)
  apt_repository:
    repo: deb {{ item.mirror }} {{ item.codename }} main contrib non-free
    state: present
    update_cache: no
    validate_certs: no
    filename: debian
  loop:
    #- { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}" }
    #- { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}-updates" }
    #- { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}-proposed-updates" }
    #- { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}-backports" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}-updates" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}-proposed-updates" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}-backports" }
  ignore_errors: true
  when: not debian_offline
