---
- name: remove {{ ansible_distribution }}:{{ ansible_distribution_version }}({{ ansible_distribution_release }}) offline repo
  yum_repository:
    name: "{{ item.split('/')[-1] }}"
    file: "{{ ansible_distribution }}{{ ansible_distribution_version }}"
    state: absent
  loop: "{{ depends_repo_url }}"

- name: "remove {{ ansible_distribution }}:{{ ansible_distribution_version }}({{ ansible_distribution_release }}) podman depends repo"
  yum_repository:
    name: "{{ item.name }}"
    file: "{{ item.file }}"
    state: absent
  loop:
    - { name: podman_depends, file: podman_depends }
