---
- name: add {{ ansible_distribution }}:{{ ansible_distribution_version }}({{ ansible_distribution_release }}) offline repo
  yum_repository:
    name: "{{ item.split('/')[-1] }}"
    description: "{{ item.split('/')[-1] }} YUM repo"
    baseurl: "{{ item }}"
    file: "{{ ansible_distribution }}{{ ansible_distribution_version }}"
    gpgcheck: no
    state: present
  loop: "{{ depends_repo_url }}"

- name: add {{ ansible_distribution }}:{{ ansible_distribution_version }}({{ ansible_distribution_release }}) podman depends repo
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: no
    state: present
  loop:
    - { name: podman_depends, file: podman_depends, description: podman depends YUM repo, baseurl: "{{ podman_repo_url }}" }
