---
- name: remove {{ ansible_distribution }}:{{ ansible_distribution_version }}({{ ansible_distribution_release }}) offline repo
  apt_repository:
    repo: deb [trusted=yes] {{ item }} {{ ansible_distribution_release }} main contrib 
    state: absent
    update_cache: no
    validate_certs: no
    filename: debian
  loop: "{{ depends_repo_url }}"
  when: depends_offline

- name: remove {{ ansible_distribution }}:{{ ansible_distribution_version }}({{ ansible_distribution_release }}) online repo (tsinghua/aliyun)
  apt_repository:
    repo: deb {{ item.mirror }} {{ item.codename }} main contrib non-free
    state: absent
    update_cache: no
    validate_certs: no
    filename: debian
  loop:
    - { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}" }
    - { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}-backports" }
    - { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}-proposed-updates" }
    - { mirror: "https://mirrors.tuna.tsinghua.edu.cn/debian/", codename: "{{ ansible_distribution_release }}-updates" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}-backports" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}-proposed-updates" }
    - { mirror: "https://mirrors.aliyun.com/debian/", codename: "{{ ansible_distribution_release }}-updates" }
  ignore_errors: true
  when: not depends_offline
