---
- name: stop containerd
  service: 
    name: containerd
    state: stopped 
    enabled: no
  ignore_errors: true

- name: filter mounted container dirs
  shell: df
  register: df_result

- name: unmount left pods 
  mount:
    path: "{{ item }}"
    state: unmounted
  loop: "{{ df_result.stdout | regex_findall('(/run/containerd/.+)') }}"
  tags: unmount_containerd

- name: remove containerd 
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/bin/containerd
    - /usr/local/bin/ctr
    - /usr/local/bin/containerd-shim-runc-v1
    - /usr/local/bin/containerd-shim-runc-v2
    - /usr/local/bin/containerd-shim
    - /usr/local/bin/containerd-stress
    - /etc/containerd
    - /lib/systemd/system/containerd.service
    - /run/containerd
    - /var/lib/containerd
    - /usr/local/bin/runc
